export const PROJECT_FORMULAR = "PROJECT_FORMULAR";
export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const ADD_PROJECT = "ADD_PROJECT";
export const VALIDATE_FORM = "VALIDATE_FORM";
export const ACTIVE_PROJECT = "ACTIVE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
